require 'pact_broker/db'
require 'pact_broker/domain/order_versions'
require 'pact_broker/repositories/helpers'

module PactBroker

  module Domain

    class Version < Sequel::Model

      set_primary_key :id
      one_to_many :pact_publications, order: :revision_number, class: "PactBroker::Pacts::PactPublication", key: :consumer_version_id
      associate(:many_to_one, :pacticipant, :class => "PactBroker::Domain::Pacticipant", :key => :pacticipant_id, :primary_key => :id)
      one_to_many :tags, :reciprocal => :version, order: :created_at

      dataset_module do
        include PactBroker::Repositories::Helpers
      end

      def after_create
        OrderVersions.(self)
      end

      def to_s
        "Version: number=#{number}, pacticipant=#{pacticipant_id}"
      end

      def version_and_updated_date
        "Version #{number} - #{updated_at.to_time.localtime.strftime("%d/%m/%Y")}"
      end

      # What about provider??? This makes no sense
      def latest_pact_publication
        pact_publications.last
      end
    end

    Version.plugin :timestamps, :update_on_create=>true
  end
end

# Table: versions
# Columns:
#  id             | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  number         | text                        |
#  repository_ref | text                        |
#  pacticipant_id | integer                     | NOT NULL
#  order          | integer                     |
#  created_at     | timestamp without time zone | NOT NULL
#  updated_at     | timestamp without time zone | NOT NULL
# Indexes:
#  versions_pkey                        | PRIMARY KEY btree (id)
#  uq_ver_ppt_ord                       | UNIQUE btree (pacticipant_id, "order")
#  versions_pacticipant_id_number_index | UNIQUE btree (pacticipant_id, number)
#  ndx_ver_num                          | btree (number)
#  ndx_ver_ord                          | btree ("order")
# Foreign key constraints:
#  versions_pacticipant_id_fkey | (pacticipant_id) REFERENCES pacticipants(id)
# Referenced By:
#  tags              | tags_version_id_fkey                       | (version_id) REFERENCES versions(id)
#  pact_publications | pact_publications_consumer_version_id_fkey | (consumer_version_id) REFERENCES versions(id)
#  verifications     | fk_verifications_versions                  | (provider_version_id) REFERENCES versions(id)
