source "https://rubygems.org"

gem "pact_broker", path: "../"
gem "sqlite3", "~>1.3" # Sqlite is just for testing. Replace this with "pg" for production.
gem "pg" # Production database gem
gem "puma", "~> 5.3" # Can be replaced with your choice of application server
