---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
    - spec/
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_patterns:
- script/
- vendor/
- public/Network Graph_files/
- public/js/bootstrap*
- public/javascripts/d3.v3.js.pagespeed.ce.dFNRrGTALe.js
- public/javascripts/highlight.pack.js
- public/javascripts/jquery*.js
- public/js/bootstrap*.js
- public/javascripts/pagination.js
- public/javascripts/material-menu.js

