version: "3"

services:
  postgres:
    image: postgres:${POSTGRES_DOCKER_IMAGE_TAG:-latest}
    logging:
        driver: none
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  tests:
    build: .
    depends_on:
      - postgres
    environment:
      PACT_BROKER_TEST_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
      PACT_BROKER_HIDE_PACTFLOW_MESSAGES: 'true'
    volumes:
      - ./lib:/home/lib
      - ./spec:/home/spec
      - ./db:/home/db
      - ./config.ru:/home/config.ru
      - ./tasks:/home/tasks
      - ./Rakefile:/home/Rakefile
      - ./config:/home/config
      - ./.rspec:/home/.rspec
      - ./.rubocop:/home/.rubocop
      - ./.gitignore:/home/.gitignore
      - ./public:/home/public
      - ./script/docker-container/test.sh:/usr/local/bin/test
      - ./docs:/home/docs
      - ./pact_broker_oas.yaml:/home/pact_broker_oas.yaml
    entrypoint: dockerize
    command: --wait tcp://postgres:5432 -timeout 60s test
