module MatrixBaseline
  # Formats a shape's captured query profile into a markdown scoreboard.
  # Each shape and each statement is wrapped in a collapsible <details> block
  # (statements nested inside their shape) so the generated file — which can be
  # very large — stays navigable and diffs stay reviewable.
  class Scoreboard
    def self.section(shape, statements, plans)
      lines = []
      lines << "<details>"
      lines << "<summary><strong>#{shape.label}</strong> (<code>#{shape.id}</code>) — #{shape.kind}, #{statements.size} queries</summary>"
      lines << ""
      statements.each_with_index do |sql, i|
        lines << "<details>"
        lines << "<summary>Statement #{i + 1} of #{statements.size}</summary>"
        lines << ""
        lines << "```sql"
        lines << sql
        lines << "```"
        lines << ""
        lines << "```"
        lines << (plans[sql] || "(no plan captured)")
        lines << "```"
        lines << ""
        lines << "</details>"
        lines << ""
      end
      lines << "</details>"
      lines << ""
      lines.join("\n")
    end

    def self.document(adapter, sections)
      header = [
        "# Matrix query baseline",
        "",
        "Adapter: #{adapter}",
        "",
        "Generated by `bundle exec rspec spec/benchmarks/matrix_baseline_spec.rb --tag matrix_baseline`.",
        "Regenerate and diff against a previous run to compare query counts and plans.",
        "",
      ].join("\n")
      ([header] + sections).join("\n")
    end
  end
end
