source 'https://rubygems.org'

gem "rake", "~>12.0"
gem "pact_broker", git: "https://github.com/pact-foundation/pact_broker.git", ref: "8783ef83730969f3fce0034f36c7cf4652dc8733"
gem "sqlite3", "~>1.3"
gem "pg"
