source 'https://rubygems.org'

gem "rake", "~>12.0"
gem "pact_broker", git: "https://github.com/pact-foundation/pact_broker.git", ref: "11d3464a120ed5f76e23241c79992fa04b702701"
gem "sqlite3", "~>1.3"
gem "pg"
