source "https://rubygems.org"

gem "rake", "~>12.0"
gem "pact_broker", git: "https://github.com/pact-foundation/pact_broker.git", ref: "11d3464a120ed5f76e23241c79992fa04b702701"
gem "webrick", "~>1.3.0" # Webrick requires Ruby version >= 2.5.0dev. TODO remove dependency on Pact gem.
gem "sqlite3", "~>1.3"
gem "pg"
