require "pact_broker/db"
require "pact_broker/repositories/helpers"

module PactBroker
  module Versions
    class Branch < Sequel::Model(:branches)
      plugin :timestamps, update_on_create: true
      plugin :insert_ignore, identifying_columns: [:name, :pacticipant_id]

      associate(:many_to_one, :pacticipant, :class => "PactBroker::Domain::Pacticipant", :key => :pacticipant_id, :primary_key => :id)
    end
  end
end

# Table: branches
# Columns:
#  id                       | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name                     | text                        |
#  pacticipant_id           | integer                     | NOT NULL
#  latest_branch_version_id | integer                     |
#  latest_version_id        | integer                     |
#  created_at               | timestamp without time zone | NOT NULL
#  updated_at               | timestamp without time zone | NOT NULL
# Indexes:
#  branches_pkey                      | PRIMARY KEY btree (id)
#  branches_name_pacticipant_id_index | UNIQUE btree (name, pacticipant_id)
# Foreign key constraints:
#  branches_pacticipant_id_fkey | (pacticipant_id) REFERENCES pacticipants(id) ON DELETE CASCADE
# Referenced By:
#  branch_heads    | branch_heads_branch_id_fkey | (branch_id) REFERENCES branches(id) ON DELETE CASCADE
#  branch_versions | branch_versions_branches_fk | (branch_id) REFERENCES branches(id) ON DELETE CASCADE
