require "bundler/setup"
require "pact_broker/tasks"

def create_connection
  require "sequel"
  database_config = {adapter: "sqlite", database: "pact_broker_database.sqlite3", :encoding => "utf8"}
  Sequel.connect(database_config)
end

PactBroker::DB::MigrationTask.new do | task |
  task.database_connection = create_connection
end

PactBroker::DB::VersionTask.new do | task |
  task.database_connection = create_connection
end

task "pact_broker:version" do
  require "pact_broker/version"
  puts PactBroker::VERSION
end
