source 'https://rubygems.org'

gem "rake", "~>12.0"
gem "pact_broker", git: "https://github.com/pact-foundation/pact_broker.git", ref: "a963fce89c44d89d00899956f218a62fa2b786c7"
gem "sqlite3", "~>1.3"
