FROM ruby:3.2-alpine@sha256:a9cc6b6548d6268c249e5f2f571a16549ed5448e7dc7152a6b22b33d631235aa

RUN apk update \
    && apk --no-cache add \
      "build-base>=0.5" \
      "bash>=4.4" \
      "ca-certificates>=20190108" \
      "git>=2.20" \
      "postgresql-dev>=11.3" \
      "sqlite-dev>=3.28" \
      "sqlite>=3.28" \
      "tzdata>=2019" \
      "mariadb-dev>=10.3" \
    && rm -rf /var/cache/apk/*

RUN apk add --no-cache openssl less

ENV DOCKERIZE_VERSION=v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz


WORKDIR /home

COPY Gemfile /home/Gemfile
COPY pact_broker.gemspec /home/pact_broker.gemspec
COPY lib/pact_broker/version.rb /home/lib/pact_broker/version.rb
COPY .gitignore /home/.gitignore

RUN gem install bundler -v '~>2.0.0' \
    && bundle install --jobs 3 --retry 3

COPY lib /home/lib
COPY db /home/db
COPY public /home/public
COPY tasks /home/tasks
COPY config.ru /home/config.ru
COPY Rakefile /home/Rakefile
COPY script  /home/script

RUN ls /home
