name: Reproduce issue

on:
  push:
    branches:
      - 'issue/**'
  pull_request:
    branches:
      - 'issue/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: docker compose -f docker-compose-issue-repro.yml up --abort-on-container-exit --exit-code-from repro-issue
